package com.example.grama_suvidha

import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.widget.Toast
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.io.IOException

object PdfGenerator {

    fun generateProjectReport(context: Context, project: Project) {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas
        val paint = Paint()

        // Title
        paint.textSize = 24f
        paint.isFakeBoldText = true
        paint.color = Color.parseColor("#1A73E8")
        canvas.drawText("Project Report: ${project.nameEn}", 50f, 50f, paint)

        // Separator line
        paint.color = Color.parseColor("#34A853")
        paint.strokeWidth = 2f
        canvas.drawLine(50f, 65f, 545f, 65f, paint)

        // Details
        paint.textSize = 14f
        paint.isFakeBoldText = false
        paint.color = Color.BLACK
        var yPos = 100f

        val details = listOf(
            "Project ID" to "#${project.id}",
            "Status" to project.statusEn,
            "Progress" to "${project.progress}%",
            "Budget" to project.budget,
            "Location" to project.locationEn,
            "Expected Completion" to project.expectedCompletion,
            "Category" to project.category
        )

        for ((label, value) in details) {
            paint.isFakeBoldText = true
            canvas.drawText("$label: ", 50f, yPos, paint)
            paint.isFakeBoldText = false
            canvas.drawText(value, 50f + paint.measureText("$label: ") + 10f, yPos, paint)
            yPos += 28f
        }

        yPos += 20f
        paint.isFakeBoldText = true
        paint.textSize = 16f
        paint.color = Color.parseColor("#1A73E8")
        canvas.drawText("Description:", 50f, yPos, paint)
        yPos += 25f
        paint.isFakeBoldText = false
        paint.textSize = 12f
        paint.color = Color.DKGRAY

        // Simple text wrap for description
        val descText = project.descriptionEn.replace("\\n", "\n")
        for (paragraph in descText.split("\n")) {
            val words = paragraph.trim().split(" ")
            var line = ""
            for (word in words) {
                if (word.isEmpty()) continue
                if (paint.measureText("$line $word") < 490f) {
                    line += "$word "
                } else {
                    canvas.drawText(line.trim(), 50f, yPos, paint)
                    yPos += 18f
                    line = "$word "
                }
            }
            if (line.isNotBlank()) {
                canvas.drawText(line.trim(), 50f, yPos, paint)
                yPos += 18f
            }
            yPos += 6f
        }

        // Footer
        yPos = 800f
        paint.textSize = 10f
        paint.color = Color.GRAY
        canvas.drawText("Generated by Grama-Suvidha Portal | ${java.text.SimpleDateFormat("dd-MM-yyyy HH:mm", java.util.Locale.getDefault()).format(java.util.Date())}", 50f, yPos, paint)

        pdfDocument.finishPage(page)

        val fileName = "GramaSuvidha_Project_${project.id}_Report.pdf"

        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                // Android 10+ : Use MediaStore to save to Downloads (visible to user)
                val contentValues = ContentValues().apply {
                    put(MediaStore.Downloads.DISPLAY_NAME, fileName)
                    put(MediaStore.Downloads.MIME_TYPE, "application/pdf")
                    put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
                }
                val resolver = context.contentResolver
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    resolver.openOutputStream(uri)?.use { outputStream ->
                        pdfDocument.writeTo(outputStream)
                    }
                    Toast.makeText(context, "✅ Report saved to Downloads!", Toast.LENGTH_LONG).show()
                    
                    // Open the PDF
                    try {
                        val viewIntent = Intent(Intent.ACTION_VIEW).apply {
                            setDataAndType(uri, "application/pdf")
                            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                        }
                        context.startActivity(viewIntent)
                    } catch (e: Exception) {
                        // No PDF viewer installed — that's okay, file is saved
                    }
                } else {
                    Toast.makeText(context, "Failed to create file in Downloads", Toast.LENGTH_SHORT).show()
                }
            } else {
                // Android 9 and below : Save to public Downloads directory
                @Suppress("DEPRECATION")
                val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                if (!downloadsDir.exists()) downloadsDir.mkdirs()
                val file = File(downloadsDir, fileName)
                pdfDocument.writeTo(FileOutputStream(file))
                Toast.makeText(context, "✅ Report saved to Downloads!", Toast.LENGTH_LONG).show()
                
                // Open the PDF
                try {
                    val uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
                    val viewIntent = Intent(Intent.ACTION_VIEW).apply {
                        setDataAndType(uri, "application/pdf")
                        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                    }
                    context.startActivity(viewIntent)
                } catch (e: Exception) {
                    // No PDF viewer or FileProvider not configured — file is still saved
                }
            }
        } catch (e: IOException) {
            e.printStackTrace()
            Toast.makeText(context, "Failed to generate PDF: ${e.message}", Toast.LENGTH_SHORT).show()
        } finally {
            pdfDocument.close()
        }
    }
}
